/**
 * ポータルのアプリ一覧 (registry)。
 *
 * 読むところ: トップ画面 (lib/portal-dashboard.js)・権限画面 (/admin/users, /admin/permissions)・
 * 準備中ページ (/apps/:appId)。
 *
 * ⚠ id は権限 (users.json の allowedApps / requireAppAccess) のキー。変えると既存ユーザーの権限が外れる。
 *   path もブックマーク・iPad のホーム画面から直接開かれているので変えない。
 *
 * 新しいアプリを足すとき:
 *   - category は下の categories から選ぶ (分類を増やすのは 1 分類が 9 枚を超えたときだけ。中原さんに相談)
 *   - summary は「何ができるか」を全角 30 字まで。開発の段階名 (Phase / M1) や旧名は書かない
 *   - keywords に旧名・別名・やりたいことを入れる (「発注対象商品シート」「プライスター」で探せるように)
 *   - icon はトップに並ぶカードどうしで重ならないものを選ぶ
 *   - node scripts/test-portal-top.mjs で書き方の抜けをチェックできる (起動時にも警告が出る)
 *
 * description は昔のカードに出していた長い説明。いまは画面に出さない開発メモとして残している。
 *
 * 設計: G:\共有ドライブ\AI_reference\システム設計\bfaithポータル_トップ画面整理_設計_20260913.md
 */

// トップ画面の分類 (上から表示順)。id の 'data' は warehouse variant が参照しているので変えない
export const categories = [
  { id: 'mgmt', name: '経営・売上分析' },
  { id: 'research', name: '商品を調べる・企画' },
  { id: 'purchasing', name: '仕入れ・発注・価格' },
  { id: 'product-sync', name: '商品登録・出品' },
  { id: 'inbound', name: '入荷・在庫化' },
  { id: 'shipping', name: '出荷作業' },
  { id: 'fba', name: 'FBA' },
  { id: 'support', name: 'お客様対応' },
  { id: 'accounting', name: '経理・会計' },
  { id: 'data', name: 'マスタ・設定' },
];

// 同じ仕事をモール別に分けたアプリは、トップでは 1 枚のカードにまとめてモール名のボタンを並べる。
// 権限はボタン (= アプリ) 単位のまま。見られるのが 1 本だけのユーザーには普通のカードで出す
export const appGroups = [
  {
    id: 'mall-analytics',
    name: 'モール別分析',
    icon: '📈',
    category: 'mgmt',
    summary: '売上・広告・利益をモールごとに見る',
    keywords: ['分析', 'ダッシュボード', '広告', 'ROAS', '利益'],
  },
  {
    id: 'mall-accounting',
    name: 'モール別 売上集計',
    icon: '🧮',
    category: 'accounting',
    summary: '注文CSVから税率別・セグメント別に集計',
    keywords: ['売上集計', '税率', 'セグメント', '会計', '月次', '経理'],
  },
];

// badges: 'ipad' | 'phone' | 'readonly' | 'admin'   status: 'active' | 'coming-soon' | 'archived'
export const apps = [
  // ── 経営・売上分析 ──
  {
    id: 'exec-dashboard',
    name: 'MF経営トップダッシュボード',
    icon: '🏛️',
    path: '/apps/exec-dashboard',
    status: 'active',
    category: 'mgmt',
    summary: '売上・粗利・現金残高を1画面で',
    keywords: ['経営', 'MF', 'マネーフォワード', '会計', '現金', '資金繰り'],
    description: 'MFクラウド会計データから売上・粗利・現金残高・モール別売上を1画面集約 (Phase 1a)',
  },
  {
    id: 'biz-ops-overview',
    name: '業務オペ概要',
    icon: '📊',
    path: '/apps/biz-ops-overview',
    status: 'active',
    category: 'mgmt',
    summary: '全モールの前日・今月の売上と出荷率',
    keywords: ['日次', 'KPI', '売上', '出荷率', '速報'],
    description: '全モール売上 (前日/今月/30日) + 出荷率等の日次経営指標集約',
  },
  {
    id: 'amazon-dashboard',
    name: 'Amazon統合ダッシュボード',
    icon: '🛒',
    path: '/apps/amazon-dashboard',
    status: 'active',
    category: 'mgmt',
    group: { id: 'mall-analytics', label: 'Amazon' },
    summary: 'Amazonの売上・広告・利益をまとめて見る',
    keywords: ['スポンサー広告'],
    description: 'Amazonの売上・広告・利益を統合管理 (タイル速報 + 利益ウォーターフォール + 広告×利益 + 売れ筋 + 診断)',
  },
  {
    id: 'rakuten-analytics',
    name: '楽天分析ツール',
    icon: '📊',
    path: '/apps/rakuten-analytics',
    status: 'active',
    category: 'mgmt',
    group: { id: 'mall-analytics', label: '楽天' },
    summary: '楽天の売上・広告・利益・検索順位',
    keywords: ['RPP', '検索順位'],
    description: '楽天の売上・広告・利益・検索順位を統合管理 (タイル速報 + 実質利益 + RPP×損益分岐ROAS + 順位重ね合わせ)',
  },
  {
    id: 'yahoo-analytics',
    name: 'ヤフー分析ツール',
    icon: '🛍️',
    path: '/apps/yahoo-analytics',
    status: 'active',
    category: 'mgmt',
    group: { id: 'mall-analytics', label: 'Yahoo!' },
    summary: 'Yahoo!の売上・広告・利益・キャンペーン',
    keywords: ['ヤフー', 'キャンペーン'],
    description: 'Yahoo!ショッピングの売上・広告・利益・検索順位を統合管理 (タイル速報 + 実質利益 + 広告×利益 + キャンペーン損益)',
  },
  {
    id: 'aupay-analytics',
    name: 'auPAY分析ツール',
    icon: '🧡',
    path: '/apps/aupay-analytics',
    status: 'active',
    category: 'mgmt',
    group: { id: 'mall-analytics', label: 'au PAY' },
    summary: 'au PAYの売上・利益・キャンペーン',
    keywords: ['auペイ', '三太郎'],
    description: 'au PAYマーケットの売上・利益・キャンペーンを統合管理 (タイル速報 + ポイント後利益L2 + 三太郎の日ハイライト + 送料負け診断)',
  },
  {
    id: 'qoo10-analytics',
    name: 'Qoo10分析ツール',
    icon: '🛒',
    path: '/apps/qoo10-analytics',
    status: 'active',
    category: 'mgmt',
    group: { id: 'mall-analytics', label: 'Qoo10' },
    summary: 'Qoo10の売上・広告・利益・メガ割損益',
    keywords: ['キューテン', 'メガ割'],
    description: 'Qoo10の売上・広告・利益・メガ割損益を統合管理 (タイル速報 + 手数料実額 + メガ割セラー負担 + 開催回損益)',
  },
  {
    id: 'sales-analytics-linegift',
    name: 'LINEギフト 売上分析ダッシュボード',
    icon: '💚',
    path: '/apps/sales-analytics-linegift',
    status: 'active',
    category: 'mgmt',
    group: { id: 'mall-analytics', label: 'LINEギフト' },
    summary: 'LINEギフトの売上・商品ランキング',
    keywords: ['母の日', 'シーン'],
    description: 'KPI / 月次トレンド / 商品ランキング / 価格帯別 / シーン(母の日等)期間絞り込み。既存 mirror_linegift_finance_sku_daily を Render で集計、商品分類は v2.0+',
  },
  {
    id: 'profit-analysis',
    name: '商品収益性ダッシュボード',
    icon: '💹',
    path: '/apps/profit-analysis',
    status: 'active',
    category: 'mgmt',
    summary: '商品別の粗利と、在庫整理・撤退の判断',
    keywords: ['粗利', '利益', '撤退', '在庫整理', '想定利益'],
    description: '商品別粗利分析 + 在庫整理・撤退判断支援',
  },
  {
    id: 'ai-insights',
    name: 'AI経営レポート設定',
    icon: '🤖',
    path: '/apps/ai-insights',
    status: 'active',
    category: 'mgmt',
    summary: '週次・月次AIレポートの予算とメモ',
    keywords: ['AI', 'GChat', '経営インサイト', '予算', 'イベント'],
    description: 'AI経営アドバイス定期配信 (週次・月次) の予算・イベントメモ・配信状態管理。レポートはGChat経営インサイトスペースへ投稿',
  },

  // ── 商品を調べる・企画 ──
  {
    id: 'product-management-list',
    name: '商品管理リスト',
    icon: '📋',
    path: '/apps/product-management-list',
    status: 'active',
    category: 'research',
    summary: '全商品の在庫・販売・利益・発注を一覧で',
    keywords: ['在庫', '販売数', '商品コード', 'NE', 'CSV'],
    description: 'NE全商品コード軸の在庫×販売(7d/30d FBA別)×利益×発注 統合表 (毎朝更新・CSV出力)',
  },
  {
    id: 'cross-sell-finder',
    name: '同梱商品検索',
    icon: '🧺',
    path: '/apps/cross-sell-finder',
    status: 'active',
    category: 'research',
    summary: '一緒に買われた商品を全モール横断で',
    keywords: ['同梱', 'ついで買い', 'クロスセル', '併売'],
    description: 'NE商品コードで過去90日に一緒に買われた商品を全モール横断で表示',
  },
  {
    id: 'ranking-checker',
    name: '楽天検索順位チェッカー',
    icon: '🏁',
    path: '/apps/ranking-checker',
    status: 'active',
    category: 'research',
    summary: 'キーワードごとの楽天の検索順位',
    keywords: ['順位', 'SEO', 'キーワード', 'ランキング'],
    description: 'キーワード別の楽天検索順位確認',
  },
  {
    id: 'product-scout',
    name: '新商品案（検索KW）',
    icon: '🔎',
    path: '/apps/product-scout/keywords',
    status: 'active',
    category: 'research',
    summary: '商品案に いい・保留・見送り を付ける',
    keywords: ['Keepa', '新商品', '企画', 'スカウト', 'キーワード'],
    description: 'Keepaと自社方針から作った商品案を確認し、いい・保留・見送りを記録。判断と理由を次の案づくりに反映します',
  },

  // ── 仕入れ・発注・価格 ──
  {
    id: 'purchase-orders',
    name: '発注補助',
    icon: '🛒',
    path: '/apps/purchase-orders',
    status: 'active',
    category: 'purchasing',
    summary: '要発注の判定から発注まで1画面で',
    keywords: ['発注', '注文', '仕入先', '発注条件', '注残', '入荷予定', '発注対象商品シート'],
    description: '仕入先への発注を1画面で完結。要発注判定・推奨発注量・最低発注条件ゲージ・ついで買い候補・発注履歴 (旧: 発注対象商品シート+発注条件マスタ)',
  },
  {
    id: 'profit-calculator',
    name: 'リサーチ仕入れツール',
    icon: '💰',
    path: '/apps/profit-calculator/',
    status: 'active',
    category: 'purchasing',
    summary: 'リサーチ・見積・利益計算をまとめて管理',
    keywords: ['リサーチ', '見積', '利益計算', '仕入れ判断'],
    description: 'リサーチ・見積もり・利益計算・商品登録の一元管理',
  },
  {
    id: 'price-update',
    name: '価格一括改定',
    icon: '💴',
    path: '/apps/price-update',
    status: 'active',
    category: 'purchasing',
    badges: ['readonly'],
    summary: '値上げ時に全モールの売価を見直す',
    keywords: ['値上げ', '売価', '価格改定', '値付け'],
    description: '値上げ時に各モールの売価を1画面で改定。出品の検索・現在価格・利益プレビュー (M1 は読み取り専用・モールへは書き込まない)',
  },
  {
    id: 'amazon-pricing',
    name: 'Amazon 価格管理',
    icon: '🏷️',
    path: '/apps/amazon-pricing/',
    status: 'active',
    category: 'purchasing',
    badges: ['readonly'],
    summary: '価格・カート・粗利を見て値付け方針を記録',
    keywords: ['プライスター', '自社プライスター', '価格', 'カート', '追従', 'ストッパー'],
    description: 'Amazon 出品の価格・カート・原価・粗利を 1 画面で見て、値付けの方針 (追従モード・ストッパー) を記録する。ルールの判定は毎日シャドーで出し人が採点。★Amazon へは書き込まない (M1)',
  },
  {
    id: 'supplier-sales',
    name: '仕入れ先 売れ筋共有',
    icon: '🤝',
    path: '/apps/supplier-sales',
    status: 'active',
    category: 'purchasing',
    summary: '仕入先別の販売実績を共有URLで渡す',
    keywords: ['仕入先', 'メーカー', '共有', '売れ筋', '販売実績'],
    description: '全モール(Amazon・楽天 ほか)の販売実績を仕入先別に集計し、ログイン不要の共有URLを発行。原価非開示・販売数/売上のみ',
  },

  // ── 商品登録・出品 ──
  {
    id: 'product-hub',
    name: '商品登録ハブ',
    icon: '🧩',
    path: '/apps/product-hub',
    status: 'active',
    category: 'product-sync',
    summary: '新商品のドラフトを作って楽天に出品',
    keywords: ['新商品', '登録', '出品', 'Notion', 'ドラフト', 'AI'],
    description: '新商品ドラフト一元管理 (Notionカード自動作成 + AI生成 + 楽天出品へ)',
  },
  {
    id: 'product-links',
    name: '商品リンク台帳',
    icon: '🔗',
    path: '/apps/product-links',
    status: 'active',
    category: 'product-sync',
    summary: '商品のCanva・画像フォルダをすぐ開く',
    keywords: ['Canva', '画像', 'Drive', 'フォルダ', 'リンク'],
    description: '全商品の Canva・画像フォルダ (Drive) リンクを商品名・コードで検索 (単品もセットも)',
  },
  {
    id: 'rakuten-yahoo-sync',
    name: '楽天→Yahoo! 商品移行',
    icon: '🟣',
    path: '/apps/rakuten-yahoo-sync',
    status: 'active',
    category: 'product-sync',
    summary: '楽天の商品をYahoo!ショッピングへ移す',
    keywords: ['Yahoo', 'ヤフー', '移行', '出品'],
    description: '楽天商品をYahoo!ショッピングへ移行 (Notion 補完 + readiness ゲート)',
  },
  {
    id: 'linegift-sync',
    name: '楽天→LINEギフト同期',
    icon: '🎁',
    path: '/apps/linegift-sync',
    status: 'active',
    category: 'product-sync',
    summary: '楽天の商品をLINEギフト形式にする',
    keywords: ['LINE', 'ギフト', '同期', '出品'],
    description: '楽天商品をLINEギフト形式に変換・同期',
  },
  {
    id: 'mercari-sync',
    name: '楽天→メルカリShops同期',
    icon: '🛍️',
    path: '/apps/mercari-sync',
    status: 'active',
    category: 'product-sync',
    summary: '楽天の商品をメルカリShops用CSVにする',
    keywords: ['メルカリ', 'CSV', '同期', '出品'],
    description: '楽天商品をメルカリShops形式に変換・CSV出力',
  },

  // ── 入荷・在庫化 ──
  {
    id: 'inbound-check',
    name: '入荷受付チェック',
    icon: '📥',
    path: '/apps/inbound-check/',
    status: 'active',
    category: 'inbound',
    badges: ['ipad'],
    summary: '届いた入荷を1タップで消し込む',
    keywords: ['入荷', '受付', 'ロジザード', '伝票', '消し込み'],
    description: 'ロジザードの入荷受付伝票 (紙) を iPad に置き換え。届いた行を1タップで消し込み、入数・ピックロケ・行き先を表示',
  },
  {
    id: 'inbound-info',
    name: '入庫情報管理',
    icon: '🗂️',
    path: '/apps/inbound-info',
    status: 'active',
    category: 'inbound',
    summary: '入数・BCシール・荷姿などの入庫マスタ',
    keywords: ['入庫情報管理表', '入数', 'BCシール', '荷姿', '値札'],
    description: '入数・BCシール・保管荷姿・いろは在庫化などの入庫マスタ。新商品はNE商品マスタから毎日自動追加 (旧: 入庫情報管理表スプレッドシート)',
  },
  {
    id: 'iroha-work',
    name: 'いろは在庫化 作業アプリ',
    icon: '🎋',
    path: '/apps/iroha-work/',
    status: 'active',
    category: 'inbound',
    badges: ['ipad'],
    summary: '在庫化カードの一覧・優先度・進み具合',
    keywords: ['いろは', '在庫化', 'Notion', 'カンバン'],
    description: 'いろはの在庫化作業をNotionカンバンからiPadへ。カード一覧・詳細・優先度 (残り在庫日数)・ステータス変更 (Notionが正本のまま連動)',
  },
  {
    id: 'giftset-assembly',
    name: 'ギフトセット組み依頼',
    icon: '🎀',
    path: '/apps/giftset-assembly',
    status: 'active',
    category: 'inbound',
    summary: '構成品のピッキング表と作業カードを出す',
    keywords: ['ギフトセット', '組み', '子会社', 'Notion'],
    description: '構成品のピッキング表(ロジザード貼り付け)と子会社Notionの作業カードを発行',
  },

  // ── 出荷作業 ──
  {
    id: 'shipping-work',
    name: '出荷作業管理',
    icon: '🏭',
    path: '/apps/shipping-work',
    status: 'active',
    category: 'shipping',
    summary: 'ピッキング・梱包の作業時間を計る',
    keywords: ['Notion', 'カンバン', '作業時間', '計測'],
    description: 'Notionカンバン置き換え。ピッキング・梱包の作業時間をボタン操作で自動計測',
  },
  {
    id: 'picking',
    name: 'ピッキング支援',
    icon: '📱',
    path: '/apps/picking',
    status: 'active',
    category: 'shipping',
    badges: ['phone'],
    summary: 'ピッキングリストをスマホで見る',
    keywords: ['トータルピッキング', 'CS03002', '欠品'],
    description: '紙のトータルピッキングリストをスマホ表示に置き換え。CS03002取込・明細単位の時間計測',
  },
  {
    id: 'packing-dispatch',
    name: '梱包機振り分け・配送方法',
    icon: '⚙️',
    path: '/apps/packing-dispatch',
    status: 'active',
    category: 'shipping',
    summary: '受注CSVの配送方法と梱包機を判定',
    keywords: ['Tapes', 'pasline', 'meltline', '受注CSV', 'NE', '配送方法'],
    description: 'NE受注CSVを取り込み、配送方法と梱包機(pasline/meltline)を判定・編集して再出力。Tapes代替',
  },
  {
    id: 'aes-pdf-sorter',
    name: 'AESラベル並び替え',
    icon: '📄',
    path: '/apps/aes-pdf-sorter',
    status: 'active',
    category: 'shipping',
    summary: 'AESの配送ラベルと納品書を並べ替え',
    keywords: ['AES', 'ラベル', '納品書', 'PDF', '送り状'],
    description: 'AES配送ラベル・納品書の自動照合・並び替え',
  },
  {
    id: 'postage',
    name: '郵便料金判定',
    icon: '📮',
    path: '/apps/postage',
    status: 'active',
    category: 'shipping',
    summary: '定形外郵便の料金区分を自動で判定',
    keywords: ['定形外', '郵便', '重量', '厚み', '規格外'],
    description: '定形外郵便の料金区分 (定形110円 / 規格内 / 規格外) を商品の重さ・厚み・資材から自動判定。重量マスタの取込と、いま何割が自動で確定できるかの確認',
  },
  {
    id: 'shipping-log',
    name: '出荷件数',
    icon: '🔢',
    path: '/apps/shipping-log',
    status: 'active',
    category: 'shipping',
    summary: '日ごとの出荷件数をモール別に',
    keywords: ['出荷数', '件数', '配送方法', '実績'],
    description: '日ごとの出荷件数をモール別・配送方法別に集計 (伝票1件=発送1件、Amazon の AES を含む)',
  },
  {
    id: 'mis-shipment',
    name: '誤出荷管理',
    icon: '⚠️',
    path: '/apps/mis-shipment',
    status: 'active',
    category: 'shipping',
    summary: '誤出荷の記録と、工程別・原因別の集計',
    keywords: ['誤出荷', 'ミス', 'クレーム'],
    description: '誤出荷の記録・分析、モール別誤出荷率と工程別/原因別の可視化 (Phase 1)',
  },

  // ── FBA ──
  {
    id: 'fba-replenishment',
    name: 'FBA在庫補充',
    icon: '📦',
    path: '/apps/fba-replenishment',
    status: 'active',
    category: 'fba',
    summary: '納品数を計算して納品プランを作る',
    keywords: ['FBA', '納品', '補充', '推奨数', '福山'],
    description: 'FBA納品の推奨数量計算・納品プラン作成',
  },
  {
    id: 'fba-box',
    name: 'FBA箱詰め記録',
    icon: '🗃️',
    path: '/apps/fba-box/admin',
    status: 'active',
    category: 'fba',
    badges: ['ipad'],
    summary: 'どの箱に何を何個入れたかを記録',
    keywords: ['箱詰め', '納品箱', 'STA', 'パックリスト', '土台', '重い'],
    description: 'FBA納品の箱詰めをいろはのiPadで記録 (紙の納品箱No手書きを置き換え)。STAパックリストExcelと突合し、どの輸送箱に何を何個入れたかを残す',
  },
  {
    id: 'fba-profitability',
    name: 'FBA収益性分析',
    icon: '📉',
    path: '/apps/fba-profitability',
    status: 'active',
    category: 'fba',
    summary: 'FBA商品の利益率と低利益の商品',
    keywords: ['利益率', '低利益'],
    description: 'FBA全商品の利益率を分析・低利益率商品を検出',
  },

  // ── お客様対応 ──
  {
    id: 'inquiry-hub',
    name: '問い合わせ管理',
    icon: '💬',
    path: '/apps/inquiry-hub',
    status: 'active',
    category: 'support',
    summary: 'メール・R-Messe・Yahoo!の問い合わせを一か所で',
    keywords: ['問合せ', 'メールディーラー', 'R-Messe', '顧客', '返品'],
    description: 'メール+楽天R-Messe+Yahoo!問い合わせの一元管理 (メールディーラー置き換え)。Step 1: 一覧/詳細/担当/メモ/検索 (read-only運用)',
  },

  // ── 経理・会計 ──
  {
    id: 'amazon-accounting',
    name: 'Amazon売上集計',
    icon: '📒',
    path: '/apps/amazon-accounting',
    status: 'active',
    category: 'accounting',
    group: { id: 'mall-accounting', label: 'Amazon' },
    summary: 'ペイメントレポートCSVから売上を集計',
    keywords: ['ペイメントレポート'],
    description: 'ペイメントレポートCSVから税率別・セグメント別の売上集計を自動計算',
  },
  {
    id: 'amazon-usa-accounting',
    name: '米国Amazon売上集計',
    icon: '🇺🇸',
    path: '/apps/amazon-usa-accounting',
    status: 'active',
    category: 'accounting',
    group: { id: 'mall-accounting', label: '米国Amazon' },
    summary: '米国Amazonの輸出売上を円に換算して集計',
    keywords: ['USA', '輸出', 'ドル'],
    description: 'Monthly Unified Transaction CSVから輸出売上をUSD→JPY換算して集計(全売上=セグメント4)',
  },
  {
    id: 'rakuten-accounting',
    name: '楽天売上集計',
    icon: '📕',
    path: '/apps/rakuten-accounting',
    status: 'active',
    category: 'accounting',
    group: { id: 'mall-accounting', label: '楽天' },
    summary: '楽天RMSの注文データから売上を集計',
    keywords: ['RMS'],
    description: '楽天RMS注文データCSVから税率別・セグメント別の売上集計を自動計算',
  },
  {
    id: 'yahoo-accounting',
    name: 'Yahoo!売上集計',
    icon: '📗',
    path: '/apps/yahoo-accounting',
    status: 'active',
    category: 'accounting',
    group: { id: 'mall-accounting', label: 'Yahoo!' },
    summary: 'Yahoo!の注文データから売上を集計',
    keywords: ['ヤフー'],
    description: 'Yahoo注文データCSVから税率別・セグメント別の売上集計を自動計算',
  },
  {
    id: 'aupay-accounting',
    name: 'auペイマーケット売上集計',
    icon: '📙',
    path: '/apps/aupay-accounting',
    status: 'active',
    category: 'accounting',
    group: { id: 'mall-accounting', label: 'au PAY' },
    summary: 'au PAYの注文データから売上を集計',
    keywords: ['auペイ'],
    description: 'auペイマーケット会計用注文データCSVから税率別・セグメント別の売上集計を自動計算',
  },
  {
    id: 'qoo10-accounting',
    name: 'Qoo10売上集計',
    icon: '📔',
    path: '/apps/qoo10-accounting',
    status: 'active',
    category: 'accounting',
    group: { id: 'mall-accounting', label: 'Qoo10' },
    summary: 'Qoo10のセリングレポートから売上を集計',
    keywords: ['キューテン'],
    description: 'Qoo10セリングレポートCSVから税率別・セグメント別の売上集計を自動計算',
  },
  {
    id: 'linegift-accounting',
    name: 'LINEギフト売上集計',
    icon: '💚',
    path: '/apps/linegift-accounting',
    status: 'active',
    category: 'accounting',
    group: { id: 'mall-accounting', label: 'LINEギフト' },
    summary: 'LINEギフトの注文CSVから売上を集計',
    keywords: ['LINE'],
    description: 'LINEギフト注文CSVから税率別・セグメント別の売上集計を自動計算',
  },
  {
    id: 'mercari-accounting',
    name: 'メルカリShops売上集計',
    icon: '🛒',
    path: '/apps/mercari-accounting',
    status: 'active',
    category: 'accounting',
    group: { id: 'mall-accounting', label: 'メルカリ' },
    summary: 'メルカリShopsの売上レポートから集計',
    keywords: ['メルカリ'],
    description: 'メルカリShops売上レポート+注文CSVから税率別・セグメント別の売上集計を自動計算',
  },
  {
    id: 'mgmt-accounting',
    name: '売上分類別粗利集計',
    icon: '📒',
    path: '/apps/mgmt-accounting',
    status: 'active',
    category: 'accounting',
    summary: '売上分類ごとの変動費と粗利 (管理会計)',
    keywords: ['管理会計', '変動費', '運賃', '資材費', '粗利'],
    description: '各モール売上データ+運賃・資材費から売上分類別の変動費・粗利益を管理会計用に集計',
  },
  {
    id: 'inventory-monthly',
    name: '月末棚卸しツール',
    icon: '🗓️',
    path: '/apps/inventory-monthly',
    status: 'active',
    category: 'accounting',
    summary: '月末の棚卸資産を原価で出す',
    keywords: ['棚卸', '在庫金額', '月末', '原価'],
    description: 'FBA在庫(発注推奨レポート)・自社倉庫CSV・発注後未着商品を集計し、税抜原価ベースの月末棚卸資産を算出・履歴保存',
  },
  {
    id: 'shohyo-links',
    name: '証憑リンク集',
    icon: '🧾',
    path: '/apps/shohyo-links',
    status: 'active',
    category: 'accounting',
    summary: '支払い先のマイページと証憑の保存先',
    keywords: ['証憑', 'MF', '仕訳', '支払い', '引き落とし', '請求書'],
    description: 'MF仕訳用の支払い先マスタ。マイページURL・証憑保存先・引き落とし日を検索して即開く',
  },

  // ── マスタ・設定 ──
  {
    id: 'staff',
    name: 'スタッフマスタ',
    icon: '👥',
    path: '/apps/staff/',
    status: 'active',
    category: 'data',
    badges: ['admin'],
    summary: 'スタッフの番号・名前・入退社',
    keywords: ['スタッフ', '社員', '人', '勤怠', 'シフト'],
    description: '「人」の正本 (スタッフ管理番号・名前・区分・入社/退職)。各アプリの名前タップはここから引く。将来の勤怠・シフトの親 (管理者のみ)',
  },
  {
    id: 'warehouse',
    name: 'データウェアハウス',
    icon: '🗄️',
    path: '/apps/warehouse',
    status: 'active',
    category: 'data',
    summary: 'SKU・原価・送料などのマスタと販売データ',
    keywords: ['SKU', '原価', '送料', 'マスタ登録', 'DB', '税率'],
    description: '社内マスターデータ基盤・販売データ蓄積・AI分析用',
  },
  {
    id: 'easy-ship',
    name: '梱包サイズマスター (Easy Ship)',
    icon: '📐',
    path: '/apps/easy-ship',
    status: 'active',
    category: 'data',
    summary: 'Easy Ship 拡張の梱包サイズ設定',
    keywords: ['Easy Ship', 'Chrome拡張', '梱包サイズ', 'Amazon'],
    description: 'Amazon Easy Ship画面でSKUごとの梱包サイズを自動選択するChrome拡張のマスター管理',
  },
  {
    id: 'select-set',
    name: '選べるセットの明細展開',
    icon: '🧷',
    path: '/apps/select-set',
    status: 'active',
    category: 'data',
    summary: '選べるセットを実商品に展開する拡張の設定',
    keywords: ['選べる', 'セット', 'NE', '引当待ち', 'Chrome拡張'],
    description: 'NEの引当待ちで「選べる〇種セット」を実SKUの明細行に展開するChrome拡張のマスター管理',
  },
];

// 外部リンク (ポータルの外にある画面)。管理者 (allowedApps: '*') のトップにだけ出す (従来どおり)
export const externalLinks = [
  {
    id: 'x-order-conditions',
    name: '発注条件参照ツール',
    icon: '📑',
    url: 'https://script.google.com/a/macros/b-faith.biz/s/AKfycbxxn6HcHZKgAKAww1k-AFMER6SVt_-PRTQp1EJoPEclBczvUKEw1VBOWPhAo0O9Z1VO1Q/exec',
    // 使っていない (2026-09-13 中原さん)。発注補助で置き換わった。検索で「しまったアプリも探す」にすると出る
    status: 'archived',
    category: 'purchasing',
    summary: '商品コード・名前で発注条件と在庫を検索',
    keywords: ['発注条件', 'GAS', 'スプレッドシート'],
    description: '商品コード/名前で発注条件・在庫を検索',
  },
  {
    id: 'x-picking-kpi',
    name: 'ピッキングKPIダッシュボード',
    icon: '⏱️',
    url: 'https://script.google.com/a/macros/b-faith.biz/s/AKfycbxKrVwCJWtZOr1lS_-rzEvamatfpZ3UV2NCDwnwlO083Vhx3Gn2T2N6H5GfPPuZCIkUhw/exec',
    status: 'active',
    category: 'shipping',
    summary: 'ピッキング作業のKPIと実績',
    keywords: ['KPI', 'GAS', 'スプレッドシート'],
    description: 'ピッキング作業のKPI・パフォーマンス分析',
  },
];

/**
 * warehouse variant (miniPC、PORTAL_VARIANT=warehouse) のトップにだけ出すカード。
 *
 * 設計判断 (Codex round 1 critical 反映、server.js から移設):
 *   apps に新しい id を足すと、認可 (requireAppAccess) の app id とズレる。/apps/warehouse 配下は
 *   requireAppAccess('warehouse') で守られているので、表示用のカードは別配列に持ち、
 *   requiresAccess で「どの allowedApps id を持つユーザーに見せるか」を明示する。
 *     - allowedApps に 'warehouse' を持つユーザー → 「マスタ登録」が見える + 押しても 403 にならない
 *     - 権限画面 (apps ベース) は無変更。認可は variant に依存しない
 *   「ユーザー管理」リンクは dashboard.ejs のヘッダーで admin にだけ出るのでここには入れない。
 */
export const warehouseVariantDashboardApps = [
  {
    id: 'warehouse-register-display', // 表示用 (key として使う程度)
    requiresAccess: 'warehouse',      // 必要な allowedApps の app id (= 既存の warehouse)
    name: 'マスタ登録',
    icon: '📋',
    path: '/apps/warehouse/register',
    status: 'active',
    category: 'data',
    summary: 'SKU・送料・原価・売上分類・税率の登録と編集',
    keywords: ['SKU', '送料', '原価', '売上分類', '税率'],
    description: 'SKU・送料・原価・売上分類・税率の登録/編集',
  },
];
